# Configuration for Rasa NLU.
# Language configuration
recipe: default.v1
language: pt

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
  token_pattern: '(?u)\b\w+\b'
- name: CRFEntityExtractor
- name: DIETClassifier
  entity_recognition: False
  epochs: 100
- name: DucklingEntityExtractor
  url: "http://duckling.rasa.com:8000"
  dimensions: ["time"]
  locale: "pt_IE"
  timezone: "America/Sao_Paulo"
  timeout : 3
- name: EntitySynonymMapper
# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 10
  epochs: 200
- name: RulePolicy

